[theme]
base = "dark"
primaryColor = "#22D3EE"
backgroundColor = "#070B12"
secondaryBackgroundColor = "#0D131D"
textColor = "#F8FAFC"
font = "sans serif"

[server]
maxUploadSize = 50
headless = true

[browser]
gatherUsageStats = false
